name: Deploy Angular App on Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Replace _redirects for production (only for full releases)
        run: |
          IS_PRERELEASE=${{ github.event.release.prerelease }}
          if [ "$IS_PRERELEASE" = "false" ]; then
            echo "This is a full release. Replacing _redirects for production..."
            cp src/public/environments/_redirects.prod src/public/_redirects
          else
            echo "This is a pre-release. Skipping _redirects replacement."
          fi

      - name: Build Angular App
        run: npm run build:prod

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify (QA or Production)
        env:
          NETLIFY_AUTH_TOKEN_QA: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_AUTH_TOKEN_PROD: ${{ secrets.NETLIFY_AUTH_TOKEN_PROD }}
          NETLIFY_PROD_SITE_ID: ${{ secrets.NETLIFY_PROD_SITE_ID }}
          NETLIFY_QA_SITE_ID: ${{ secrets.NETLIFY_QA_SITE_ID }}
        run: |
          RELEASE_TAG="${{ github.event.release.tag_name }}"
          RELEASE_NAME="${{ github.event.release.name }}"
          IS_PRERELEASE=${{ github.event.release.prerelease }}

          echo "Release: $RELEASE_NAME ($RELEASE_TAG)"
          echo "Pre-release: $IS_PRERELEASE"

          if [ "$IS_PRERELEASE" = "true" ]; then
            echo "Deploying pre-release to QA..."
            export NETLIFY_AUTH_TOKEN="$NETLIFY_AUTH_TOKEN_QA"
            netlify deploy --dir=dist/chamanguitech --site="$NETLIFY_QA_SITE_ID" --prod --message "Pre-release: $RELEASE_NAME ($RELEASE_TAG)"
          else
            echo "Deploying full release to Production..."
            export NETLIFY_AUTH_TOKEN="$NETLIFY_AUTH_TOKEN_PROD"
            netlify deploy --dir=dist/chamanguitech --site="$NETLIFY_PROD_SITE_ID" --prod --message "Release: $RELEASE_NAME ($RELEASE_TAG)"
          fi
